#!/bin/sh

i=1
for monitor in $(bspc query -M); do
bspc monitor $monitor \
        -n "$i" \
        -d $i/{i,ii,iii,iv,v,vi,vii,viii,ix,x}
    let i++
done
NMON=$i
unset i

bspc config top_padding 16 

# Visual options
bspc config split_ratio         0.50
bspc config border_width        1
bspc config window_gap          4
bspc config borderless_monocle  true
bspc config gapless_monocle     true
bspc config focus_follows_pointer true
bspc config auto_alternate true
bspc config auto_cancel true
bspc config normal_border_color "#504339"
bspc config active_border_color "#504339"
bspc config focused_border_color "#817267"
bspc config presel_border_color "#9a875f"
bspc config urgent_border_color "#504339"
bspc config focused_locked_border_color "#8c644c"
bspc config normal_frame_opacity 0.0
bspc config focused_frame_opacity 0.1


# Rules
bspc rule -a Gimp desktop=^3 floating=on
bspc rule -a Spacefm desktop=^4
bspc rule -a Emacs desktop=^2
bspc rule -a Skype desktop=^3 floating=on
bspc rule -a Firefox desktop=^1
bspc rule -a Terminator desktop=^3 floating=on

$HOME/.config/bspwm/panel/dzen.sh &
